services:
  recommendarr:
    # IF NOT using a reverse proxy uncomment the image tag to use prebuilt
    image: tannermiddleton/recommendarr:latest
    # For reverse proxy setup uncomment and setup the URLs:
    # build:
    #   context: .
    #   args:
    #    # Build time arguments - set these for the Vue.js build process
    #    # Only needed for reverse proxy setup:
    #    # - BASE_URL=${BASE_URL:-/}
    container_name: recommendarr
    ports:
      - "${PORT:-3000}:${PORT:-3000}"  # Unified port for both frontend and API
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - NODE_ENV=production
      - DOCKER_ENV=true
      - PORT=${PORT:-3000}
      # Runtime environment variables
      # For reverse proxy setups, uncomment and modify these do NOT forget the build section above
      #- PUBLIC_URL=https://recommendarr.yourdomain.com
      - PUBLIC_URL=${PUBLIC_URL:-http://localhost:${PORT:-3000}}
    volumes:
      - recommendarr-data:/app/server/data
    restart: unless-stopped

volumes:
  recommendarr-data: