services:
  recommendarr:
    image: tannermiddleton/recommendarr:latest
    build:
      context: .
      args:
        # Build time arguments - set these for the Vue.js build process
        - VUE_APP_API_URL=${VUE_APP_API_URL:-}
        - BASE_URL=${BASE_URL:-}
    container_name: recommendarr
    ports:
      - "3030:3030"
      - "3050:3050"
    environment:
      - NODE_ENV=production
      - DOCKER_ENV=true
      # Runtime environment variables
      - PUBLIC_URL=${PUBLIC_URL:-}
    volumes:
      - ${PWD}/server/data:/app/server/data
    restart: unless-stopped