services:
  recommendarr:
    # For standard local setup (no reverse proxy):
    # Use image: tannermiddleton/recommendarr:latest
    
    # For reverse proxy setup:
    # Comment out image and use build with proper environment variables
    # image: ${USE_PREBUILT_IMAGE:-tannermiddleton/recommendarr:latest}
    
    # This build section is used only when image is commented out
    # It's used automatically when USE_PREBUILT_IMAGE is empty
    build:
      context: .
      args:
        # Build time arguments - set these for the Vue.js build process
        - VUE_APP_API_URL=${BUILD_API_URL:-http://localhost:3050}
        - BASE_URL=${BASE_URL:-/}
    
    container_name: recommendarr
    ports:
      - "3030:3030"  # Frontend port - must be 3030:3030
      - "3050:3050"  # Backend API port - must be 3050:3050
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - NODE_ENV=production
      - DOCKER_ENV=true
      # Runtime environment variables
      - PUBLIC_URL=${PUBLIC_URL:-http://localhost:3030}
      - VUE_APP_API_URL=${RUNTIME_API_URL:-http://localhost:3050}
    volumes:
      - recommendarr-data:/app/server/data
    restart: unless-stopped

volumes:
  recommendarr-data: